export const siege_004 = {
    id: 'siege_004',
    name: 'Old Watchtower',
    worldId: 'world1',
    shotLimit: 8,
    parShots: 4,
    playerStartX: 160,
    startingAngle: 43,
    startingPower: 62,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'light',
    terrainRoughness: 'smooth',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'Drop the watchtower base and the roof crashes onto the core.',
    blocks: [
        { id: 'wt_base_left',   material: 'wood', x: 760, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'wt_base_mid',    material: 'wood', x: 820, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'wt_base_right',  material: 'wood', x: 880, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'wt_core',        type: 'castle_core', material: 'crystal', x: 770, y: 480, width: 130, height: 54, hp: 42, tags: ['castle_core', 'objective'] },
        { id: 'wt_guard_right', material: 'wood', x: 900, y: 478, width: 40, height: 56, tags: ['guard'] },
        { id: 'wt_roof_left',   material: 'wood', x: 800, y: 440, width: 60, height: 40, tags: ['cover'] },
        { id: 'wt_roof_right',  material: 'wood', x: 860, y: 440, width: 60, height: 40, tags: ['cover'] },
    ],
};
