export const siege_007 = {
    id: 'siege_007',
    name: 'Sheltered Core',
    worldId: 'world1',
    shotLimit: 9,
    parShots: 5,
    playerStartX: 160,
    startingAngle: 44,
    startingPower: 70,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'gusty',
    terrainRoughness: 'smooth',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'Layered cover. Peel the outside before the core is exposed.',
    blocks: [
        { id: 'sh_floor',    material: 'wood', x: 740, y: 534, width: 200, height: 38, tags: ['foundation'] },
        { id: 'sh_lwall',    material: 'wood', x: 740, y: 478, width: 36, height: 56, tags: ['wall'] },
        { id: 'sh_rwall',    material: 'wood', x: 904, y: 478, width: 36, height: 56, tags: ['wall'] },
        { id: 'sh_inner_l',  material: 'wood', x: 776, y: 478, width: 32, height: 56, tags: ['inner'] },
        { id: 'sh_inner_r',  material: 'wood', x: 872, y: 478, width: 32, height: 56, tags: ['inner'] },
        { id: 'sh_core',     type: 'castle_core', material: 'crystal', x: 808, y: 482, width: 64, height: 52, hp: 52, tags: ['castle_core', 'objective'] },
        { id: 'sh_roof_l',   material: 'wood', x: 740, y: 442, width: 100, height: 36, tags: ['cover', 'roof'] },
        { id: 'sh_roof_r',   material: 'wood', x: 840, y: 442, width: 100, height: 36, tags: ['cover', 'roof'] },
    ],
};
