export const siege_006 = {
    id: 'siege_006',
    name: 'Stacked Tower',
    worldId: 'world1',
    shotLimit: 9,
    parShots: 4,
    playerStartX: 160,
    startingAngle: 56,
    startingPower: 72,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'light',
    terrainRoughness: 'smooth',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'Tall, narrow, top-heavy. Cracking the lower trunk drops everything above.',
    blocks: [
        { id: 'tw_b1', material: 'wood', x: 830, y: 534, width: 70, height: 38, tags: ['foundation', 'trunk'] },
        { id: 'tw_b2', material: 'wood', x: 830, y: 496, width: 70, height: 38, tags: ['trunk'] },
        { id: 'tw_b3', material: 'wood', x: 830, y: 458, width: 70, height: 38, tags: ['trunk'] },
        { id: 'tw_b4', material: 'wood', x: 830, y: 420, width: 70, height: 38, tags: ['trunk'] },
        { id: 'tw_b5', material: 'wood', x: 830, y: 382, width: 70, height: 38, tags: ['trunk'] },
        { id: 'tw_core', type: 'castle_core', material: 'crystal', x: 826, y: 340, width: 78, height: 42, hp: 46, tags: ['castle_core', 'objective'] },
        { id: 'tw_finial_l', material: 'wood', x: 800, y: 308, width: 36, height: 32, tags: ['ornament'] },
        { id: 'tw_finial_r', material: 'wood', x: 900, y: 308, width: 36, height: 32, tags: ['ornament'] },
    ],
};
