export const siege_008 = {
    id: 'siege_008',
    name: 'Outpost Citadel',
    worldId: 'world1',
    shotLimit: 10,
    parShots: 6,
    playerStartX: 160,
    startingAngle: 50,
    startingPower: 74,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'gusty',
    terrainRoughness: 'medium',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'World 1 finale. Cover, supports, and a guarded core. Mind your shots.',
    blocks: [
        { id: 'oc_b_l',     material: 'wood', x: 740, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'oc_b_ml',    material: 'wood', x: 800, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'oc_b_mr',    material: 'wood', x: 860, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'oc_b_r',     material: 'wood', x: 920, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'oc_pillar_l', material: 'wood', x: 752, y: 462, width: 36, height: 72, tags: ['wall'] },
        { id: 'oc_pillar_r', material: 'wood', x: 932, y: 462, width: 36, height: 72, tags: ['wall'] },
        { id: 'oc_floor',    material: 'wood', x: 788, y: 480, width: 144, height: 30, tags: ['floor'] },
        { id: 'oc_core',     type: 'castle_core', material: 'crystal', x: 808, y: 432, width: 104, height: 48, hp: 64, tags: ['castle_core', 'objective'] },
        { id: 'oc_cap_l',    material: 'wood', x: 788, y: 396, width: 60, height: 36, tags: ['cover', 'cap'] },
        { id: 'oc_cap_r',    material: 'wood', x: 872, y: 396, width: 60, height: 36, tags: ['cover', 'cap'] },
        { id: 'oc_pennant_l', material: 'wood', x: 740, y: 432, width: 16, height: 30, tags: ['ornament'] },
        { id: 'oc_pennant_r', material: 'wood', x: 964, y: 432, width: 16, height: 30, tags: ['ornament'] },
    ],
};
