export const siege_015 = {
    id: 'siege_015',
    name: 'Quarry Keep',
    worldId: 'world2',
    shotLimit: 11,
    parShots: 7,
    playerStartX: 180,
    startingAngle: 48,
    startingPower: 76,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'gusty',
    terrainRoughness: 'medium',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'A serious stone keep. Wood seams are your friend.',
    blocks: [
        { id: 'qk_base_l',  material: 'stone', x: 730, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'qk_base_ml', material: 'wood',  x: 790, y: 534, width: 48, height: 38, tags: ['foundation', 'weakpoint'] },
        { id: 'qk_base_mr', material: 'wood',  x: 838, y: 534, width: 48, height: 38, tags: ['foundation', 'weakpoint'] },
        { id: 'qk_base_r',  material: 'stone', x: 886, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'qk_lwall',   material: 'stone', x: 738, y: 460, width: 36, height: 74, tags: ['wall'] },
        { id: 'qk_rwall',   material: 'stone', x: 902, y: 460, width: 36, height: 74, tags: ['wall'] },
        { id: 'qk_inner_l', material: 'wood',  x: 776, y: 488, width: 50, height: 46, tags: ['support', 'weakpoint'] },
        { id: 'qk_inner_r', material: 'wood',  x: 854, y: 488, width: 50, height: 46, tags: ['support', 'weakpoint'] },
        { id: 'qk_floor',   material: 'stone', x: 774, y: 460, width: 130, height: 28, tags: ['floor'] },
        { id: 'qk_core',    type: 'castle_core', material: 'crystal', x: 780, y: 408, width: 118, height: 52, hp: 70, tags: ['castle_core', 'objective'] },
        { id: 'qk_cap_l',   material: 'stone', x: 738, y: 374, width: 100, height: 34, tags: ['roof', 'heavy'] },
        { id: 'qk_cap_r',   material: 'stone', x: 838, y: 374, width: 100, height: 34, tags: ['roof', 'heavy'] },
    ],
};
