export const siege_016 = {
    id: 'siege_016',
    name: 'Stronghold',
    worldId: 'world2',
    shotLimit: 12,
    parShots: 8,
    playerStartX: 180,
    startingAngle: 50,
    startingPower: 78,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'gusty',
    terrainRoughness: 'medium',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'World 2 finale. Mostly stone, scarce wood. Make every shot count.',
    blocks: [
        { id: 'st_b_l',     material: 'stone', x: 720, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'st_b_ml',    material: 'wood',  x: 780, y: 534, width: 44, height: 38, tags: ['foundation', 'weakpoint'] },
        { id: 'st_b_m',     material: 'stone', x: 824, y: 534, width: 52, height: 38, tags: ['foundation'] },
        { id: 'st_b_mr',    material: 'wood',  x: 876, y: 534, width: 44, height: 38, tags: ['foundation', 'weakpoint'] },
        { id: 'st_b_r',     material: 'stone', x: 920, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'st_outer_l', material: 'stone', x: 728, y: 442, width: 36, height: 92, tags: ['wall'] },
        { id: 'st_outer_r', material: 'stone', x: 936, y: 442, width: 36, height: 92, tags: ['wall'] },
        { id: 'st_floor',   material: 'stone', x: 764, y: 488, width: 172, height: 30, tags: ['floor'] },
        { id: 'st_inner_l', material: 'wood',  x: 776, y: 436, width: 40, height: 52, tags: ['support', 'weakpoint'] },
        { id: 'st_inner_r', material: 'wood',  x: 884, y: 436, width: 40, height: 52, tags: ['support', 'weakpoint'] },
        { id: 'st_core',    type: 'castle_core', material: 'crystal', x: 798, y: 392, width: 104, height: 56, hp: 86, tags: ['castle_core', 'objective'] },
        { id: 'st_cap_l',   material: 'stone', x: 764, y: 358, width: 86, height: 34, tags: ['roof', 'heavy'] },
        { id: 'st_cap_r',   material: 'stone', x: 850, y: 358, width: 86, height: 34, tags: ['roof', 'heavy'] },
    ],
};
