export const siege_012 = {
    id: 'siege_012',
    name: 'The Vault',
    worldId: 'world2',
    shotLimit: 10,
    parShots: 5,
    playerStartX: 180,
    startingAngle: 52,
    startingPower: 74,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'light',
    terrainRoughness: 'smooth',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'A stone vault. Crack a corner and the roof drops onto the core.',
    blocks: [
        { id: 'v_floor',    material: 'stone', x: 760, y: 534, width: 200, height: 38, tags: ['foundation'] },
        { id: 'v_lwall',    material: 'stone', x: 760, y: 468, width: 32, height: 66, tags: ['wall'] },
        { id: 'v_rwall',    material: 'stone', x: 928, y: 468, width: 32, height: 66, tags: ['wall'] },
        { id: 'v_ceil_l',   material: 'stone', x: 760, y: 432, width: 100, height: 36, tags: ['roof', 'heavy'] },
        { id: 'v_ceil_r',   material: 'stone', x: 860, y: 432, width: 100, height: 36, tags: ['roof', 'heavy'] },
        { id: 'v_core',     type: 'castle_core', material: 'crystal', x: 800, y: 480, width: 120, height: 54, hp: 60, tags: ['castle_core', 'objective'] },
        { id: 'v_brace',    material: 'wood', x: 792, y: 468, width: 16, height: 64, tags: ['weakpoint'] },
    ],
};
