export const siege_010 = {
    id: 'siege_010',
    name: 'Hard Wall',
    worldId: 'world2',
    shotLimit: 9,
    parShots: 4,
    playerStartX: 180,
    startingAngle: 58,
    startingPower: 78,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'light',
    terrainRoughness: 'smooth',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'Stone takes more than one shot. Or arc your shells over it.',
    blocks: [
        { id: 'hw_wall_low',  material: 'stone', x: 770, y: 472, width: 40, height: 100, tags: ['wall', 'shield'] },
        { id: 'hw_wall_high', material: 'stone', x: 770, y: 392, width: 40, height: 80, tags: ['wall', 'shield'] },
        { id: 'hw_floor',     material: 'wood', x: 810, y: 534, width: 140, height: 38, tags: ['foundation'] },
        { id: 'hw_left',      material: 'wood', x: 818, y: 478, width: 36, height: 56, tags: ['support'] },
        { id: 'hw_right',     material: 'wood', x: 906, y: 478, width: 36, height: 56, tags: ['support'] },
        { id: 'hw_core',      type: 'castle_core', material: 'crystal', x: 824, y: 432, width: 116, height: 46, hp: 50, tags: ['castle_core', 'objective'] },
        { id: 'hw_roof',      material: 'wood', x: 810, y: 400, width: 140, height: 32, tags: ['cover'] },
    ],
};
