export const siege_014 = {
    id: 'siege_014',
    name: 'Layered Defense',
    worldId: 'world2',
    shotLimit: 10,
    parShots: 6,
    playerStartX: 180,
    startingAngle: 46,
    startingPower: 72,
    objective: { type: 'destroy_core', targetTag: 'castle_core' },
    windMode: 'gusty',
    terrainRoughness: 'medium',
    loadout: [{ weaponId: 'standard', ammo: Infinity }],
    hint: 'Stone armor, wood gaps. Shoot the gaps.',
    blocks: [
        { id: 'ld_base_l', material: 'stone', x: 740, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'ld_base_m', material: 'wood',  x: 800, y: 534, width: 80, height: 38, tags: ['foundation', 'weakpoint'] },
        { id: 'ld_base_r', material: 'stone', x: 880, y: 534, width: 60, height: 38, tags: ['foundation'] },
        { id: 'ld_mid_l',  material: 'wood',  x: 752, y: 482, width: 36, height: 52, tags: ['support', 'weakpoint'] },
        { id: 'ld_mid_r',  material: 'wood',  x: 892, y: 482, width: 36, height: 52, tags: ['support', 'weakpoint'] },
        { id: 'ld_inner',  material: 'stone', x: 788, y: 482, width: 104, height: 52, tags: ['armor'] },
        { id: 'ld_core',   type: 'castle_core', material: 'crystal', x: 800, y: 434, width: 80, height: 48, hp: 58, tags: ['castle_core', 'objective'] },
        { id: 'ld_roof_l', material: 'stone', x: 760, y: 400, width: 90, height: 34, tags: ['cover', 'heavy'] },
        { id: 'ld_roof_r', material: 'stone', x: 850, y: 400, width: 90, height: 34, tags: ['cover', 'heavy'] },
    ],
};
