export const GAME_VERSION = 'v0.8.0';
export const MAX_SHIELD = 60;

export const WEAPON_CATEGORIES = {
    BASIC: 'Basic Shells',
    HEAVY: 'Heavy Explosives',
    TERRAIN_BUILDERS: 'Terrain Builders',
    TERRAIN_DESTROYERS: 'Terrain Destroyers',
    FIRE: 'Fire Weapons',
    SPLIT: 'Split / Cluster Weapons',
    ROLLING: 'Rolling Weapons',
    PRECISION: 'Precision Weapons',
    UTILITY: 'Utility / Defense',
};

export const CONFIG = {
    debug: false,
    canvas: {
        width: 1280,
        height: 720,
    },
    physics: {
        gravity: 520,
        windAccelScale: 30,
        projectileStep: 1 / 120,
    },
    wind: {
        min: -3,
        max: 3,
    },
    windModes: {
        off: { label: 'Off', min: 0, max: 0 },
        light: { label: 'Light', min: -1.2, max: 1.2 },
        normal: { label: 'Normal', min: -3, max: 3 },
        wild: { label: 'Wild', min: -5, max: 5 },
    },
    tank: {
        maxHealth: 100,
        width: 44,
        height: 18,
        barrelLength: 31,
        barrelThickness: 5,
        minAngle: 5,
        maxAngle: 85,
        minPower: 12,
        maxPower: 100,
        powerToSpeed: 6,
        spawnMargin: 120,
        movementFuelPerTurn: 90,
        moveSpeed: 150,
        maxClimbDelta: 24,
        minTankSeparation: 58,
    },
    terrain: {
        padHalfWidth: 32,
        minSpawnDistance: 460,
        roughness: {
            smooth: { label: 'Smooth', variation: 42, rolling: 20, small: 6, smoothing: 6 },
            normal: { label: 'Normal', variation: 70, rolling: 32, small: 13, smoothing: 4 },
            rough: { label: 'Rough', variation: 92, rolling: 46, small: 20, smoothing: 2 },
        },
    },
    turn: {
        cpuThinkSeconds: 0.85,
        cpuThinkJitterSeconds: 0.45,
        impactDelaySeconds: 1.05,
    },
    cpu: {
        baseAngleError: 6,
        basePowerError: 8,
        missLearning: 0.13,
        lastMissPowerCorrection: 0.032,
    },
    economy: {
        damageMoneyDivisor: 2,
        winBonus: 75,
        survivalBonus: 25,
        baseAllowance: 50,
        startingMoney: {
            none: 0,
            low: 100,
            normal: 150,
            high: 250,
        },
    },
    utilities: {
        shieldPurchaseCharge: 60,
        shieldMaxCharge: MAX_SHIELD,
        shieldAbsorbRatio: 0.5,
        // First Aid Kit fully restores health between rounds (v0.6).
        firstAidFullHeal: true,
        fallDamageDropThreshold: 32,
        fallDamageScale: 0.55,
        fallDamageMax: 45,
        parachuteReduction: 0.9,
        parachuteMinPreventedDamage: 6,
        rebuildHealthAfterDeath: 50,
    },
    // Ammo shop cards are generated from the weapon catalog. Utility items
    // stay separate because they are not selected/fired like ammo weapons.
    shop: {
        shield: {
            label: 'Shield Charge',
            price: 85,
            description: 'Adds extra damage absorption.',
            shortDescription: 'Extra damage absorption',
            stats: ['Shield: +60', `Max: ${MAX_SHIELD}`],
        },
        repair: {
            label: 'First Aid Kit',
            price: 110,
            description: 'Fully heals at the next round start if damaged.',
            shortDescription: 'Full heal next round',
            stats: ['Heal: Full', 'Use: Between rounds'],
        },
        parachute: {
            label: 'Parachute',
            price: 35,
            description: 'Automatically reduces heavy fall damage after terrain collapses.',
            shortDescription: 'Heavy fall protection',
            stats: ['Fall protection', 'Auto-use'],
        },
    },
    settings: {
        storageKey: 'tank-artillery-settings',
        defaults: {
            roundsToWin: 3,
            cpuDifficulty: 'normal',
            windMode: 'normal',
            startingMoney: 'none',
            terrainRoughness: 'normal',
        },
    },
};

export const CPU_DIFFICULTY = {
    easy: {
        label: 'Easy',
        aimErrorDegrees: [10, 16],
        powerErrorPercent: [18, 28],
        thinkingDelayMs: [900, 1400],
        shotSamples: 4,
        heavyShellUseChance: 0.10,
        dirtBombUseChance: 0.12,
        rollerUseChance: 0.12,
        napalmUseChance: 0.10,
        clusterUseChance: 0.08,
        megaUseChance: 0.02,
        shieldBuyChance: 0.15,
        repairBuyChance: 0.25,
        ammoBuyChance: 0.30,
        reserveMoney: 60,
    },
    normal: {
        label: 'Normal',
        aimErrorDegrees: [5, 9],
        powerErrorPercent: [10, 16],
        thinkingDelayMs: [700, 1100],
        shotSamples: 8,
        heavyShellUseChance: 0.25,
        dirtBombUseChance: 0.08,
        rollerUseChance: 0.20,
        napalmUseChance: 0.18,
        clusterUseChance: 0.14,
        megaUseChance: 0.05,
        shieldBuyChance: 0.35,
        repairBuyChance: 0.55,
        ammoBuyChance: 0.55,
        reserveMoney: 45,
    },
    hard: {
        label: 'Hard',
        aimErrorDegrees: [2, 5],
        powerErrorPercent: [4, 9],
        thinkingDelayMs: [500, 900],
        shotSamples: 14,
        heavyShellUseChance: 0.45,
        dirtBombUseChance: 0.05,
        rollerUseChance: 0.28,
        napalmUseChance: 0.24,
        clusterUseChance: 0.24,
        megaUseChance: 0.10,
        shieldBuyChance: 0.65,
        repairBuyChance: 0.80,
        ammoBuyChance: 0.75,
        reserveMoney: 30,
    },
};

// `ammo` remains for existing call sites; `maxAmmo` and `unlimitedAmmo` are the
// catalog fields used by new shop, CPU, balance, and validation helpers.
export const WEAPONS = [
    {
        id: 'standard',
        name: 'Standard Shell',
        compactName: 'Std',
        inventoryName: 'Standard Shell',
        category: WEAPON_CATEGORIES.BASIC,
        role: 'baseline',
        behavior: 'crater',
        ammo: Infinity,
        maxAmmo: Infinity,
        startingAmmo: Infinity,
        unlimitedAmmo: true,
        price: null,
        shopRefillPrice: null,
        damage: 38,
        maxDamage: 38,
        damageRadius: 42,
        damageFalloff: 1.15,
        terrainEffect: 'crater',
        terrainEffectType: 'crater',
        terrainRadius: 42,
        explosionRadius: 42,
        terrainEffectRadius: 42,
        terrainEffectStrength: 0.92,
        speedScale: 1,
        projectileRadius: 4,
        color: '#b8c0c2',
        trailColor: '220, 228, 230',
        impactVisual: 'blast',
        visualType: 'medium expanding blast',
        fireSoundType: 'standard',
        impactSoundType: 'standard',
        iconProfile: { shape: 'shell', accent: '#d7e1e4' },
        visualProfile: { projectile: 'shell', impact: 'blast', trailLength: 18, screenShake: 2.2 },
        soundProfile: { fire: 'standard', impact: 'standard' },
        cpuUseWeight: 1,
        shopPriority: 0,
        arcDifficulty: 'Easy',
        damageLabel: 'Medium',
        craterLabel: 'Medium',
        terrainLabel: 'Crater',
        terrainMessage: 'Standard Shell cratered the ground.',
        description: 'Reliable unlimited basic shot.',
        shortDescription: 'Reliable unlimited basic shot',
        shopDescription: 'Reliable unlimited fallback shot.',
        statTags: ['Damage: Medium', 'Crater: Medium', 'Ammo: Unlimited', 'Arc: Standard'],
    },
    {
        id: 'precision',
        name: 'Precision Shell',
        compactName: 'Prec',
        inventoryName: 'Precision Shells',
        category: WEAPON_CATEGORIES.PRECISION,
        role: 'precision',
        behavior: 'crater',
        ammo: 4,
        maxAmmo: 4,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 95,
        shopRefillPrice: 95,
        damage: 58,
        maxDamage: 58,
        damageRadius: 28,
        damageFalloff: 2.25,
        terrainEffect: 'small crater',
        terrainEffectType: 'crater',
        terrainRadius: 22,
        explosionRadius: 34,
        terrainEffectRadius: 22,
        terrainEffectStrength: 0.52,
        speedScale: 1.04,
        projectileRadius: 3.6,
        color: '#dfe9f0',
        trailColor: '235, 246, 255',
        impactVisual: 'precisionSpark',
        visualType: 'tight flash and small crater',
        fireSoundType: 'precision',
        impactSoundType: 'precision',
        iconProfile: { shape: 'dart', accent: '#f7fbff' },
        visualProfile: { projectile: 'dart', impact: 'precisionSpark', trailLength: 20, screenShake: 1.8 },
        soundProfile: { fire: 'precision', impact: 'precision' },
        cpuUseWeight: 0.72,
        shopPriority: 12,
        arcDifficulty: 'Medium',
        damageLabel: 'High direct',
        craterLabel: 'Tiny',
        terrainLabel: 'Small crater',
        terrainMessage: 'Precision Shell punched a narrow crater.',
        description: 'Small blast radius with higher direct-hit damage.',
        shortDescription: 'Small crater, strong direct hit',
        shopDescription: 'Rewards accurate shots with high direct damage.',
        statTags: ['Damage: Direct high', 'Crater: Tiny', 'Ammo: 4', 'Arc: Fast'],
    },
    {
        id: 'heavy',
        name: 'Heavy Shell',
        compactName: 'Heavy',
        inventoryName: 'Heavy Shells',
        category: WEAPON_CATEGORIES.HEAVY,
        role: 'heavyDamage',
        behavior: 'crater',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 1,
        unlimitedAmmo: false,
        price: 100,
        shopRefillPrice: 100,
        damage: 70,
        maxDamage: 70,
        damageRadius: 68,
        damageFalloff: 1.35,
        terrainEffect: 'large crater',
        terrainEffectType: 'crater',
        terrainRadius: 66,
        explosionRadius: 72,
        terrainEffectRadius: 66,
        terrainEffectStrength: 1.36,
        speedScale: 0.94,
        projectileRadius: 6,
        color: '#667078',
        trailColor: '188, 198, 204',
        impactVisual: 'heavyBlast',
        visualType: 'large expanding blast',
        fireSoundType: 'heavy',
        impactSoundType: 'heavy',
        iconProfile: { shape: 'heavyShell', accent: '#aeb9c0' },
        visualProfile: { projectile: 'heavyShell', impact: 'heavyBlast', trailLength: 26, screenShake: 4.2 },
        soundProfile: { fire: 'heavy', impact: 'heavy' },
        cpuUseWeight: 0.82,
        shopPriority: 20,
        arcDifficulty: 'Medium-heavy',
        damageLabel: 'High',
        craterLabel: 'Large',
        terrainLabel: 'Large crater',
        terrainMessage: 'Heavy Shell caused a major blast.',
        description: 'Stronger blast and larger crater; heavier arc than Standard.',
        shortDescription: 'High damage, heavier arc',
        shopDescription: 'Reliable power shot with a heavier arc than Standard.',
        statTags: ['Damage: High', 'Crater: Large', 'Ammo: 3', 'Arc: Heavy'],
    },
    {
        // v0.6: Dirt Bomb buffed to ~3x visible mound effect (wider radius +
        // taller mound with reduced post-smoothing).
        id: 'dirt',
        name: 'Dirt Bomb',
        compactName: 'Dirt',
        inventoryName: 'Dirt Bombs',
        category: WEAPON_CATEGORIES.TERRAIN_BUILDERS,
        role: 'terrainBuild',
        behavior: 'addTerrain',
        ammo: 4,
        maxAmmo: 4,
        startingAmmo: 1,
        unlimitedAmmo: false,
        price: 80,
        shopRefillPrice: 80,
        damage: 10,
        maxDamage: 10,
        damageRadius: 34,
        damageFalloff: 1.7,
        terrainEffect: 'mound',
        terrainEffectType: 'mound',
        terrainRadius: 88,
        explosionRadius: 70,
        terrainEffectRadius: 88,
        terrainEffectStrength: 92,
        speedScale: 0.92,
        projectileRadius: 6,
        color: '#8a5b32',
        trailColor: '130, 110, 68',
        impactVisual: 'dirtPuff',
        visualType: 'dirt puff',
        fireSoundType: 'dirt',
        impactSoundType: 'dirt',
        iconProfile: { shape: 'dirtBall', accent: '#b47941' },
        visualProfile: { projectile: 'dirtBall', impact: 'dirtPuff', trailLength: 18, screenShake: 2.6 },
        soundProfile: { fire: 'dirt', impact: 'dirt' },
        cpuUseWeight: 0.24,
        shopPriority: 30,
        arcDifficulty: 'Medium-heavy',
        damageLabel: 'Low',
        craterLabel: 'None',
        terrainLabel: 'Adds mound',
        terrainMessage: 'Dirt Bomb piled up a large mound.',
        description: 'Adds terrain and reshapes cover.',
        shortDescription: 'Adds terrain cover',
        shopDescription: 'Basic terrain-building cover tool.',
        statTags: ['Damage: Low', 'Terrain: Adds mound', 'Ammo: 4'],
    },
    {
        id: 'mound',
        name: 'Mound Maker',
        compactName: 'Mound',
        inventoryName: 'Mound Makers',
        category: WEAPON_CATEGORIES.TERRAIN_BUILDERS,
        role: 'terrainBuild',
        behavior: 'addTerrain',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 110,
        shopRefillPrice: 110,
        damage: 6,
        maxDamage: 6,
        damageRadius: 30,
        damageFalloff: 1.85,
        terrainEffect: 'large mound',
        terrainEffectType: 'mound',
        terrainRadius: 112,
        explosionRadius: 82,
        terrainEffectRadius: 112,
        terrainEffectStrength: 126,
        speedScale: 0.88,
        projectileRadius: 6.4,
        color: '#6f8b43',
        trailColor: '118, 130, 72',
        impactVisual: 'dirtPuff',
        visualType: 'large dirt-and-grass mound',
        fireSoundType: 'mound',
        impactSoundType: 'mound',
        iconProfile: { shape: 'mound', accent: '#9ab45f' },
        visualProfile: { projectile: 'mound', impact: 'dirtPuff', trailLength: 18, screenShake: 2.4 },
        soundProfile: { fire: 'mound', impact: 'mound' },
        cpuUseWeight: 0.16,
        shopPriority: 34,
        arcDifficulty: 'Heavy',
        damageLabel: 'Very low',
        craterLabel: 'None',
        terrainLabel: 'Large mound',
        terrainMessage: 'Mound Maker raised a thick berm.',
        description: 'Builds a larger focused mound for cover or traps.',
        shortDescription: 'Builds a larger mound',
        shopDescription: 'Focused defensive terrain builder.',
        statTags: ['Damage: Very low', 'Terrain: Large mound', 'Ammo: 3'],
    },
    {
        id: 'excavator',
        name: 'Excavator Bomb',
        compactName: 'Excav',
        inventoryName: 'Excavator Bombs',
        category: WEAPON_CATEGORIES.TERRAIN_DESTROYERS,
        role: 'terrainDestroy',
        behavior: 'crater',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 115,
        shopRefillPrice: 115,
        damage: 26,
        maxDamage: 26,
        damageRadius: 48,
        damageFalloff: 1.35,
        terrainEffect: 'deep crater',
        terrainEffectType: 'crater',
        terrainRadius: 86,
        explosionRadius: 70,
        terrainEffectRadius: 86,
        terrainEffectStrength: 1.7,
        speedScale: 0.92,
        projectileRadius: 6,
        color: '#a47b54',
        trailColor: '170, 126, 80',
        impactVisual: 'excavatorBlast',
        visualType: 'soil-heavy blast',
        fireSoundType: 'excavator',
        impactSoundType: 'excavator',
        iconProfile: { shape: 'drillBomb', accent: '#c79a64' },
        visualProfile: { projectile: 'drillBomb', impact: 'excavatorBlast', trailLength: 18, screenShake: 3.4 },
        soundProfile: { fire: 'excavator', impact: 'excavator' },
        cpuUseWeight: 0.42,
        shopPriority: 38,
        arcDifficulty: 'Heavy',
        damageLabel: 'Low-medium',
        craterLabel: 'Very large',
        terrainLabel: 'Digs terrain',
        terrainMessage: 'Excavator Bomb dug out a wide cut.',
        description: 'Low damage bomb that removes a lot of terrain.',
        shortDescription: 'Digs out terrain',
        shopDescription: 'Opens sight lines and drops cover with modest damage.',
        statTags: ['Damage: Low', 'Crater: Very large', 'Ammo: 3'],
    },
    {
        id: 'roller',
        name: 'Roller Shell',
        compactName: 'Roller',
        inventoryName: 'Roller Shells',
        category: WEAPON_CATEGORIES.ROLLING,
        role: 'rolling',
        behavior: 'roller',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 90,
        shopRefillPrice: 90,
        damage: 42,
        maxDamage: 42,
        damageRadius: 42,
        damageFalloff: 1.2,
        terrainEffect: 'small crater',
        terrainEffectType: 'crater',
        terrainRadius: 36,
        explosionRadius: 46,
        terrainEffectRadius: 36,
        terrainEffectStrength: 0.82,
        rollerBehavior: { minSpeed: 58, maxSpeed: 128, friction: 18, slopeAccel: 0.35, maxAge: 2.8, obstructionDelta: 18 },
        speedScale: 0.9,
        projectileRadius: 5,
        color: '#b9c4c9',
        trailColor: '205, 218, 224',
        impactVisual: 'rollerBlast',
        visualType: 'rolling shell',
        fireSoundType: 'roller',
        impactSoundType: 'roller',
        iconProfile: { shape: 'roller', accent: '#d8e2e6' },
        visualProfile: { projectile: 'roller', impact: 'rollerBlast', trailLength: 18, screenShake: 2.2 },
        soundProfile: { fire: 'roller', impact: 'roller' },
        cpuUseWeight: 0.58,
        shopPriority: 46,
        arcDifficulty: 'Terrain-dependent',
        damageLabel: 'Medium',
        craterLabel: 'Small',
        terrainLabel: 'Rolling crater',
        terrainMessage: 'Roller Shell carved a rolling blast crater.',
        description: 'Rolls along slopes before exploding.',
        shortDescription: 'Rolls along slopes',
        shopDescription: 'Basic slope-following weapon for downhill targets.',
        statTags: ['Damage: Medium', 'Crater: Small', 'Ammo: 3'],
    },
    {
        id: 'heavyRoller',
        name: 'Heavy Roller',
        compactName: 'HRoll',
        inventoryName: 'Heavy Rollers',
        category: WEAPON_CATEGORIES.ROLLING,
        role: 'rollingHeavy',
        behavior: 'roller',
        ammo: 2,
        maxAmmo: 2,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 150,
        shopRefillPrice: 150,
        damage: 56,
        maxDamage: 56,
        damageRadius: 52,
        damageFalloff: 1.28,
        terrainEffect: 'rolling crater',
        terrainEffectType: 'crater',
        terrainRadius: 46,
        explosionRadius: 58,
        terrainEffectRadius: 46,
        terrainEffectStrength: 1.08,
        rollerBehavior: { minSpeed: 48, maxSpeed: 112, friction: 12, slopeAccel: 0.44, maxAge: 3.25, obstructionDelta: 22 },
        speedScale: 0.84,
        projectileRadius: 6.8,
        color: '#474f59',
        trailColor: '156, 168, 176',
        impactVisual: 'heavyRollerBlast',
        visualType: 'heavy rolling shell',
        fireSoundType: 'heavyRoller',
        impactSoundType: 'heavyRoller',
        iconProfile: { shape: 'heavyRoller', accent: '#a8b2ba' },
        visualProfile: { projectile: 'heavyRoller', impact: 'heavyRollerBlast', trailLength: 22, screenShake: 3.6 },
        soundProfile: { fire: 'heavyRoller', impact: 'heavyRoller' },
        cpuUseWeight: 0.36,
        shopPriority: 50,
        arcDifficulty: 'Hard',
        damageLabel: 'Medium-high',
        craterLabel: 'Medium',
        terrainLabel: 'Rolling crater',
        terrainMessage: 'Heavy Roller ground into the slope before detonating.',
        description: 'Heavier rolling weapon that travels slopes before detonating.',
        shortDescription: 'Heavier slope roller',
        shopDescription: 'Limited heavy roller for downhill or uneven approaches.',
        statTags: ['Damage: Medium-high', 'Crater: Medium', 'Ammo: 2'],
    },
    {
        id: 'napalm',
        name: 'Napalm Canister',
        compactName: 'Napalm',
        inventoryName: 'Napalm Canisters',
        category: WEAPON_CATEGORIES.FIRE,
        role: 'fire',
        behavior: 'napalm',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 95,
        shopRefillPrice: 95,
        damage: 36,
        maxDamage: 36,
        damageRadius: 78,
        damageFalloff: 1.05,
        terrainEffect: 'scorch',
        terrainEffectType: 'scorch',
        terrainRadius: 0,
        explosionRadius: 74,
        terrainEffectRadius: 0,
        terrainEffectStrength: 0,
        flameWidth: 152,
        flameDuration: 2.35,
        burnTicks: 2,
        burnDamage: 1,
        burnTickInterval: 0.45,
        speedScale: 0.94,
        projectileRadius: 5,
        color: '#ff5d35',
        trailColor: '255, 124, 62',
        impactVisual: 'napalmFlame',
        visualType: 'terrain-hugging flame patch',
        fireSoundType: 'napalm',
        impactSoundType: 'napalm',
        iconProfile: { shape: 'canister', accent: '#ffb354' },
        visualProfile: { projectile: 'canister', impact: 'napalmFlame', trailLength: 18, screenShake: 2.2 },
        soundProfile: { fire: 'napalm', impact: 'napalm' },
        cpuUseWeight: 0.5,
        shopPriority: 58,
        arcDifficulty: 'Medium-heavy',
        damageLabel: 'Medium',
        craterLabel: 'None',
        terrainLabel: 'Scorch + burn',
        terrainMessage: 'Napalm Canister scorched the ridge with minimal terrain damage.',
        description: 'Initial flame hit plus small burn ticks; little terrain damage.',
        shortDescription: 'Flame hit plus burn ticks',
        shopDescription: 'Fire-area pressure with two small burn ticks.',
        statTags: ['Damage: Medium', 'Burn: 2 x -1', 'Terrain: Scorch', 'Ammo: 3'],
    },
    {
        id: 'firestorm',
        name: 'Firestorm Canister',
        compactName: 'FStorm',
        inventoryName: 'Firestorm Canisters',
        category: WEAPON_CATEGORIES.FIRE,
        role: 'fireHeavy',
        behavior: 'napalm',
        ammo: 2,
        maxAmmo: 2,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 180,
        shopRefillPrice: 180,
        damage: 42,
        maxDamage: 42,
        damageRadius: 96,
        damageFalloff: 1.08,
        terrainEffect: 'wide scorch',
        terrainEffectType: 'scorch',
        terrainRadius: 0,
        explosionRadius: 92,
        terrainEffectRadius: 0,
        terrainEffectStrength: 0,
        flameWidth: 214,
        flameDuration: 2.7,
        burnTicks: 3,
        burnDamage: 1,
        burnTickInterval: 0.42,
        speedScale: 0.9,
        projectileRadius: 6,
        color: '#f0442f',
        trailColor: '255, 92, 42',
        impactVisual: 'firestormFlame',
        visualType: 'wide terrain fire patch',
        fireSoundType: 'firestorm',
        impactSoundType: 'firestorm',
        iconProfile: { shape: 'firestormCanister', accent: '#ffd36f' },
        visualProfile: { projectile: 'firestormCanister', impact: 'firestormFlame', trailLength: 22, screenShake: 3.4 },
        soundProfile: { fire: 'firestorm', impact: 'firestorm' },
        cpuUseWeight: 0.28,
        shopPriority: 62,
        arcDifficulty: 'Heavy',
        damageLabel: 'Medium area',
        craterLabel: 'None',
        terrainLabel: 'Wide burn',
        terrainMessage: 'Firestorm Canister spread a wide burning line.',
        description: 'Expensive wide fire-area weapon with modest burn pressure.',
        shortDescription: 'Wide fire area',
        shopDescription: 'Limited area-denial fire with bounded burn ticks.',
        statTags: ['Damage: Area', 'Burn: 3 x -1', 'Terrain: Scorch', 'Ammo: 2'],
    },
    {
        id: 'airburst',
        name: 'Airburst Shell',
        compactName: 'Air',
        inventoryName: 'Airburst Shells',
        category: WEAPON_CATEGORIES.PRECISION,
        role: 'airburst',
        behavior: 'airburst',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 120,
        shopRefillPrice: 120,
        damage: 34,
        maxDamage: 34,
        damageRadius: 76,
        damageFalloff: 1.15,
        terrainEffect: 'airburst crater',
        terrainEffectType: 'airburst',
        terrainRadius: 36,
        explosionRadius: 62,
        terrainEffectRadius: 36,
        terrainEffectStrength: 0.58,
        airburstBehavior: { minAge: 0.34, triggerRadius: 96, height: 38, terrainOffset: 8 },
        speedScale: 0.98,
        projectileRadius: 4.2,
        color: '#75d5ff',
        trailColor: '155, 224, 255',
        impactVisual: 'airburstPulse',
        visualType: 'overhead pulse blast',
        fireSoundType: 'airburst',
        impactSoundType: 'airburst',
        iconProfile: { shape: 'airburst', accent: '#b9f0ff' },
        visualProfile: { projectile: 'airburst', impact: 'airburstPulse', trailLength: 24, screenShake: 2.1 },
        soundProfile: { fire: 'airburst', impact: 'airburst' },
        cpuUseWeight: 0.42,
        shopPriority: 70,
        arcDifficulty: 'Medium',
        damageLabel: 'Medium area',
        craterLabel: 'Small',
        terrainLabel: 'Overhead blast',
        terrainMessage: 'Airburst Shell popped above the ridge and chipped the ground.',
        description: 'Explodes above terrain or near exposed tanks for partial area damage.',
        shortDescription: 'Overhead area pop',
        shopDescription: 'Pressure tool for exposed tanks and small ridge cover.',
        statTags: ['Damage: Area', 'Crater: Small', 'Ammo: 3', 'Arc: Standard'],
    },
    {
        id: 'splitter',
        name: 'Splitter Shell',
        compactName: 'Split',
        inventoryName: 'Splitter Shells',
        category: WEAPON_CATEGORIES.SPLIT,
        role: 'controlledFork',
        behavior: 'splitter',
        ammo: 3,
        maxAmmo: 3,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 125,
        shopRefillPrice: 125,
        damage: 24,
        maxDamage: 24,
        damageRadius: 34,
        damageFalloff: 1.18,
        terrainEffect: 'split craters',
        terrainEffectType: 'split',
        terrainRadius: 22,
        explosionRadius: 34,
        terrainEffectRadius: 22,
        terrainEffectStrength: 0.48,
        clusterCount: 3,
        splitPattern: 'controlledFork',
        splitCount: 3,
        splitAt: 'apex',
        spreadType: 'predictable',
        splitBehavior: {
            childId: 'splitterShard',
            childName: 'Splitter Shard',
            childCompactName: 'Shard',
            count: 3,
            pattern: 'controlledFork',
            splitAt: 'apex',
            spreadType: 'predictable',
            minAge: 0.46,
            triggerVy: -8,
            forwardVxScale: 0.78,
            forkVxScale: 0.66,
            forkSpreadScale: 0.18,
            childDownKick: 62,
            childDamage: 20,
            childDamageRadius: 30,
            childTerrainRadius: 22,
            childTerrainStrength: 0.44,
            childExplosionRadius: 32,
            childProjectileRadius: 3.6,
            childColor: '#a9f1d4',
            childTrailColor: '175, 246, 218',
            childImpactVisual: 'splitterSpark',
            childTerrainMessage: 'Splitter shard cut a small crater.',
        },
        speedScale: 0.94,
        projectileRadius: 5.2,
        color: '#7fe0bb',
        trailColor: '140, 234, 201',
        impactVisual: 'splitterSpark',
        visualType: 'three timed shards',
        fireSoundType: 'splitter',
        impactSoundType: 'splitter',
        iconProfile: { shape: 'splitter', accent: '#b6ffdf' },
        visualProfile: { projectile: 'splitter', impact: 'splitterSpark', trailLength: 20, screenShake: 2 },
        soundProfile: { fire: 'splitter', impact: 'splitter' },
        cpuUseWeight: 0.42,
        shopPriority: 74,
        arcDifficulty: 'Medium-hard',
        damageLabel: 'Controlled fork',
        craterLabel: 'Small fork',
        terrainLabel: 'Three child shells',
        terrainMessage: 'Splitter Shell forked into controlled child craters.',
        description: 'Controlled mid-air fork into three child shells near the top of the arc.',
        shortDescription: 'Controlled fork shot',
        shopDescription: 'Forks into controlled child shells near the top of its arc.',
        statTags: ['Damage: Controlled fork', 'Crater: Small fork', 'Ammo: 3'],
    },
    {
        id: 'cluster',
        name: 'Cluster Bomb',
        compactName: 'Cluster',
        inventoryName: 'Cluster Bombs',
        category: WEAPON_CATEGORIES.SPLIT,
        role: 'cluster',
        behavior: 'cluster',
        ammo: 2,
        maxAmmo: 2,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 130,
        shopRefillPrice: 130,
        damage: 28,
        maxDamage: 28,
        damageRadius: 34,
        damageFalloff: 1.2,
        terrainEffect: 'cluster craters',
        terrainEffectType: 'split',
        terrainRadius: 24,
        explosionRadius: 34,
        terrainEffectRadius: 24,
        terrainEffectStrength: 0.55,
        clusterCount: 5,
        bomblets: 5,
        splitPattern: 'wideScatter',
        bombletCount: 5,
        spreadType: 'area',
        bombletMaxDamage: 18,
        bombletDamageRadius: 24,
        bombletTerrainRadius: 20,
        clusterSplitMinAge: 0.38,
        splitBehavior: {
            childId: 'clusterBomblet',
            childName: 'Cluster Bomblet',
            childCompactName: 'Bomblet',
            count: 5,
            pattern: 'wideScatter',
            spreadType: 'area',
            minAge: 0.38,
            triggerVy: -20,
            spreadScale: 0.62,
            childVxScale: 0.32,
            childVyScale: 0.34,
            randomSpread: 0.2,
            childDamage: 18,
            childDamageRadius: 24,
            childTerrainRadius: 20,
            childTerrainStrength: 0.46,
            childExplosionRadius: 26,
            childProjectileRadius: 3.5,
            childColor: '#ffe28a',
            childTrailColor: '255, 224, 138',
            childImpactVisual: 'clusterMiniBlast',
            childTerrainMessage: 'Cluster bomblet made a small crater.',
        },
        speedScale: 0.9,
        projectileRadius: 6,
        color: '#d7c771',
        trailColor: '230, 210, 110',
        impactVisual: 'clusterMiniBlast',
        visualType: 'split bomblets',
        fireSoundType: 'cluster',
        impactSoundType: 'cluster',
        iconProfile: { shape: 'cluster', accent: '#ffe28a' },
        visualProfile: { projectile: 'cluster', impact: 'clusterMiniBlast', trailLength: 20, screenShake: 2 },
        soundProfile: { fire: 'cluster', impact: 'cluster' },
        cpuUseWeight: 0.4,
        shopPriority: 78,
        arcDifficulty: 'Hard',
        damageLabel: 'Wide spread',
        craterLabel: 'Small cluster',
        terrainLabel: 'Five bomblets',
        terrainMessage: 'Cluster Bomb peppered the terrain with small craters.',
        description: 'Splits into several bomblets for wide area coverage.',
        shortDescription: 'Wide bomblet coverage',
        shopDescription: 'Splits into several bomblets for wide area coverage.',
        statTags: ['Damage: Wide spread', 'Crater: Small cluster', 'Ammo: 2'],
    },
    {
        id: 'mega',
        name: 'Mega Bomb',
        compactName: 'Mega',
        inventoryName: 'Mega Bombs',
        category: WEAPON_CATEGORIES.HEAVY,
        role: 'premium',
        behavior: 'crater',
        ammo: 1,
        maxAmmo: 1,
        startingAmmo: 0,
        unlimitedAmmo: false,
        price: 375,
        shopRefillPrice: 375,
        damage: 82,
        maxDamage: 82,
        damageRadius: 82,
        damageFalloff: 1.85,
        terrainEffect: 'massive crater',
        terrainEffectType: 'crater',
        terrainRadius: 88,
        explosionRadius: 92,
        terrainEffectRadius: 88,
        terrainEffectStrength: 1.62,
        speedScale: 0.92,
        projectileRadius: 7,
        color: '#2b3036',
        trailColor: '255, 108, 54',
        impactVisual: 'megaBlast',
        visualType: 'largest expanding blast',
        fireSoundType: 'mega',
        impactSoundType: 'mega',
        iconProfile: { shape: 'megaShell', accent: '#ffcf3f' },
        visualProfile: { projectile: 'megaShell', impact: 'megaBlast', trailLength: 26, screenShake: 6 },
        soundProfile: { fire: 'mega', impact: 'mega' },
        cpuUseWeight: 0.12,
        shopPriority: 96,
        arcDifficulty: 'Very heavy',
        damageLabel: 'Extreme',
        craterLabel: 'Massive',
        terrainLabel: 'Massive crater',
        terrainMessage: 'Mega Bomb tore open a massive crater.',
        description: 'Late-match super weapon with huge blast.',
        shortDescription: 'Huge blast, late-game',
        shopDescription: 'Late-match premium blast; max ammo 1.',
        statTags: ['Damage: Extreme', 'Crater: Massive', 'Ammo: 1', 'Arc: Very heavy'],
    },
];

export function getWeaponById(id) {
    return WEAPONS.find((weapon) => weapon.id === id) || WEAPONS[0];
}

export function weaponMaxAmmo(weapon) {
    if (!weapon) return 0;
    if (weapon.unlimitedAmmo) return Infinity;
    const max = weapon.maxAmmo ?? weapon.ammo;
    return Number.isFinite(max) ? max : Infinity;
}

export function weaponPrice(weapon) {
    if (!weapon || weapon.unlimitedAmmo) return null;
    return weapon.price ?? weapon.shopRefillPrice ?? null;
}

export function clamp(value, min, max) {
    return Math.max(min, Math.min(max, value));
}

export function clampShieldCharge(value) {
    const numeric = Number(value);
    return Number.isFinite(numeric) ? clamp(numeric, 0, MAX_SHIELD) : 0;
}

export function maxAmmoFor(weaponId) {
    const weapon = getWeaponById(weaponId);
    return weapon ? weaponMaxAmmo(weapon) : 0;
}

export function limitedWeapons() {
    return WEAPONS.filter((weapon) => Number.isFinite(weaponMaxAmmo(weapon)));
}
