export const GAME_VERSION = 'v0.6.10';

export const CONFIG = {
    debug: false,
    canvas: {
        width: 1280,
        height: 720,
    },
    physics: {
        gravity: 520,
        windAccelScale: 30,
        projectileStep: 1 / 120,
    },
    wind: {
        min: -3,
        max: 3,
    },
    windModes: {
        off: { label: 'Off', min: 0, max: 0 },
        light: { label: 'Light', min: -1.2, max: 1.2 },
        normal: { label: 'Normal', min: -3, max: 3 },
        wild: { label: 'Wild', min: -5, max: 5 },
    },
    tank: {
        maxHealth: 100,
        width: 44,
        height: 18,
        barrelLength: 31,
        barrelThickness: 5,
        minAngle: 5,
        maxAngle: 85,
        minPower: 12,
        maxPower: 100,
        powerToSpeed: 6,
        spawnMargin: 120,
        movementFuelPerTurn: 90,
        moveSpeed: 150,
        maxClimbDelta: 24,
        minTankSeparation: 58,
    },
    terrain: {
        padHalfWidth: 32,
        minSpawnDistance: 460,
        roughness: {
            smooth: { label: 'Smooth', variation: 42, rolling: 20, small: 6, smoothing: 6 },
            normal: { label: 'Normal', variation: 70, rolling: 32, small: 13, smoothing: 4 },
            rough: { label: 'Rough', variation: 92, rolling: 46, small: 20, smoothing: 2 },
        },
    },
    turn: {
        cpuThinkSeconds: 0.85,
        cpuThinkJitterSeconds: 0.45,
        impactDelaySeconds: 1.05,
    },
    cpu: {
        baseAngleError: 6,
        basePowerError: 8,
        missLearning: 0.13,
        lastMissPowerCorrection: 0.032,
    },
    economy: {
        damageMoneyDivisor: 2,
        winBonus: 75,
        survivalBonus: 25,
        baseAllowance: 50,
        startingMoney: {
            none: 0,
            low: 100,
            normal: 150,
            high: 250,
        },
    },
    utilities: {
        shieldPurchaseCharge: 60,
        shieldMaxCharge: 180,
        shieldAbsorbRatio: 0.5,
        // First Aid Kit fully restores health between rounds (v0.6).
        firstAidFullHeal: true,
        fallDamageDropThreshold: 32,
        fallDamageScale: 0.55,
        fallDamageMax: 45,
        parachuteReduction: 0.9,
        parachuteMinPreventedDamage: 6,
        rebuildHealthAfterDeath: 50,
    },
    // Existing ammo shop entries stay explicit so their IDs and shop identity
    // remain stable; added limited weapons are generated from WEAPONS.
    shop: {
        heavyAmmo: { label: 'Heavy Shell Ammo', refillLabel: 'Heavy Shell Ammo', fullLabel: 'Heavy Shell Ammo Full', price: 100, weaponId: 'heavy' },
        dirtAmmo: { label: 'Dirt Bomb Ammo', refillLabel: 'Dirt Bomb Ammo', fullLabel: 'Dirt Bomb Ammo Full', price: 80, weaponId: 'dirt' },
        shield: {
            label: 'Shield Charge',
            price: 85,
            description: 'Adds extra damage absorption.',
            shortDescription: 'Extra damage absorption',
            stats: ['Shield: +60', 'Max: 180'],
        },
        repair: {
            label: 'First Aid Kit',
            price: 110,
            description: 'Fully heals at the next round start if damaged.',
            shortDescription: 'Full heal next round',
            stats: ['Heal: Full', 'Use: Between rounds'],
        },
        parachute: {
            label: 'Parachute',
            price: 35,
            description: 'Automatically reduces heavy fall damage after terrain collapses.',
            shortDescription: 'Heavy fall protection',
            stats: ['Fall protection', 'Auto-use'],
        },
    },
    settings: {
        storageKey: 'tank-artillery-settings',
        defaults: {
            roundsToWin: 3,
            cpuDifficulty: 'normal',
            windMode: 'normal',
            startingMoney: 'none',
            terrainRoughness: 'normal',
        },
    },
};

export const CPU_DIFFICULTY = {
    easy: {
        label: 'Easy',
        aimErrorDegrees: [10, 16],
        powerErrorPercent: [18, 28],
        thinkingDelayMs: [900, 1400],
        shotSamples: 4,
        heavyShellUseChance: 0.10,
        dirtBombUseChance: 0.12,
        rollerUseChance: 0.12,
        napalmUseChance: 0.10,
        clusterUseChance: 0.08,
        megaUseChance: 0.02,
        shieldBuyChance: 0.15,
        repairBuyChance: 0.25,
        ammoBuyChance: 0.30,
        reserveMoney: 60,
    },
    normal: {
        label: 'Normal',
        aimErrorDegrees: [5, 9],
        powerErrorPercent: [10, 16],
        thinkingDelayMs: [700, 1100],
        shotSamples: 8,
        heavyShellUseChance: 0.25,
        dirtBombUseChance: 0.08,
        rollerUseChance: 0.20,
        napalmUseChance: 0.18,
        clusterUseChance: 0.14,
        megaUseChance: 0.05,
        shieldBuyChance: 0.35,
        repairBuyChance: 0.55,
        ammoBuyChance: 0.55,
        reserveMoney: 45,
    },
    hard: {
        label: 'Hard',
        aimErrorDegrees: [2, 5],
        powerErrorPercent: [4, 9],
        thinkingDelayMs: [500, 900],
        shotSamples: 14,
        heavyShellUseChance: 0.45,
        dirtBombUseChance: 0.05,
        rollerUseChance: 0.28,
        napalmUseChance: 0.24,
        clusterUseChance: 0.24,
        megaUseChance: 0.10,
        shieldBuyChance: 0.65,
        repairBuyChance: 0.80,
        ammoBuyChance: 0.75,
        reserveMoney: 30,
    },
};

// `ammo` doubles as the carried-max for refill purchases (Infinity = unlimited).
export const WEAPONS = [
    {
        id: 'standard',
        name: 'Standard Shell',
        compactName: 'Std',
        inventoryName: 'Standard Shell',
        behavior: 'crater',
        ammo: Infinity,
        startingAmmo: Infinity,
        shopRefillPrice: null,
        maxDamage: 38,
        damageRadius: 42,
        damageFalloff: 1.15,
        terrainEffectType: 'crater',
        explosionRadius: 42,
        terrainEffectRadius: 42,
        terrainEffectStrength: 0.92,
        speedScale: 1,
        projectileRadius: 4,
        color: '#b8c0c2',
        trailColor: '220, 228, 230',
        impactVisual: 'blast',
        visualType: 'medium expanding blast',
        fireSoundType: 'standard',
        impactSoundType: 'standard',
        terrainMessage: 'Standard Shell cratered the ground.',
        description: 'Reliable unlimited basic shot.',
        shortDescription: 'Reliable unlimited basic shot',
        statTags: ['Damage: Medium', 'Crater: Medium', 'Ammo: Unlimited', 'Arc: Standard'],
    },
    {
        id: 'heavy',
        name: 'Heavy Shell',
        compactName: 'Heavy',
        inventoryName: 'Heavy Shells',
        behavior: 'crater',
        ammo: 3,
        startingAmmo: 1,
        shopRefillPrice: 100,
        maxDamage: 70,
        damageRadius: 68,
        damageFalloff: 1.35,
        terrainEffectType: 'crater',
        explosionRadius: 72,
        terrainEffectRadius: 66,
        terrainEffectStrength: 1.36,
        speedScale: 0.94,
        projectileRadius: 6,
        color: '#667078',
        trailColor: '188, 198, 204',
        impactVisual: 'heavyBlast',
        visualType: 'large expanding blast',
        fireSoundType: 'heavy',
        impactSoundType: 'heavy',
        terrainMessage: 'Heavy Shell caused a major blast.',
        description: 'Stronger blast and larger crater; heavier arc than Standard.',
        shortDescription: 'High damage, heavier arc',
        statTags: ['Damage: High', 'Crater: Large', 'Ammo: 3', 'Arc: Heavy'],
    },
    {
        // v0.6: Dirt Bomb buffed to ~3x visible mound effect (wider radius +
        // taller mound with reduced post-smoothing).
        id: 'dirt',
        name: 'Dirt Bomb',
        compactName: 'Dirt',
        inventoryName: 'Dirt Bombs',
        behavior: 'addTerrain',
        ammo: 4,
        startingAmmo: 1,
        shopRefillPrice: 80,
        maxDamage: 10,
        damageRadius: 34,
        damageFalloff: 1.7,
        terrainEffectType: 'mound',
        explosionRadius: 70,
        terrainEffectRadius: 88,
        terrainEffectStrength: 92,
        speedScale: 0.92,
        projectileRadius: 6,
        color: '#8a5b32',
        trailColor: '130, 110, 68',
        impactVisual: 'dirtPuff',
        visualType: 'dirt puff',
        fireSoundType: 'dirt',
        impactSoundType: 'dirt',
        terrainMessage: 'Dirt Bomb piled up a large mound.',
        description: 'Adds terrain and reshapes cover.',
        shortDescription: 'Adds terrain cover',
        statTags: ['Damage: Low', 'Terrain: Adds mound', 'Ammo: 4'],
    },
    {
        id: 'roller',
        name: 'Roller Shell',
        compactName: 'Roller',
        inventoryName: 'Roller Shells',
        behavior: 'roller',
        ammo: 3,
        startingAmmo: 0,
        shopRefillPrice: 90,
        maxDamage: 42,
        damageRadius: 42,
        damageFalloff: 1.2,
        terrainEffectType: 'crater',
        explosionRadius: 46,
        terrainEffectRadius: 36,
        terrainEffectStrength: 0.82,
        speedScale: 0.9,
        projectileRadius: 5,
        color: '#b9c4c9',
        trailColor: '205, 218, 224',
        impactVisual: 'rollerBlast',
        visualType: 'rolling shell',
        fireSoundType: 'roller',
        impactSoundType: 'roller',
        terrainMessage: 'Roller Shell carved a rolling blast crater.',
        description: 'Rolls along slopes before exploding.',
        shortDescription: 'Rolls along slopes',
        statTags: ['Damage: Medium', 'Crater: Small', 'Ammo: 3'],
    },
    {
        id: 'napalm',
        name: 'Napalm Canister',
        compactName: 'Napalm',
        inventoryName: 'Napalm Canisters',
        behavior: 'napalm',
        ammo: 3,
        startingAmmo: 0,
        shopRefillPrice: 95,
        maxDamage: 36,
        damageRadius: 78,
        damageFalloff: 1.05,
        terrainEffectType: 'scorch',
        explosionRadius: 74,
        terrainEffectRadius: 0,
        terrainEffectStrength: 0,
        flameWidth: 152,
        flameDuration: 2.35,
        burnTicks: 2,
        burnDamage: 1,
        burnTickInterval: 0.45,
        speedScale: 0.94,
        projectileRadius: 5,
        color: '#ff5d35',
        trailColor: '255, 124, 62',
        impactVisual: 'napalmFlame',
        visualType: 'terrain-hugging flame patch',
        fireSoundType: 'napalm',
        impactSoundType: 'napalm',
        terrainMessage: 'Napalm Canister scorched the ridge with minimal terrain damage.',
        description: 'Initial flame hit plus small burn ticks; little terrain damage.',
        shortDescription: 'Flame hit plus burn ticks',
        statTags: ['Damage: Medium', 'Burn: 2 x -1', 'Terrain: Scorch', 'Ammo: 3'],
    },
    {
        id: 'cluster',
        name: 'Cluster Bomb',
        compactName: 'Cluster',
        inventoryName: 'Cluster Bombs',
        behavior: 'cluster',
        ammo: 2,
        startingAmmo: 0,
        shopRefillPrice: 130,
        maxDamage: 28,
        damageRadius: 34,
        damageFalloff: 1.2,
        terrainEffectType: 'split',
        explosionRadius: 34,
        terrainEffectRadius: 24,
        terrainEffectStrength: 0.55,
        bomblets: 5,
        bombletMaxDamage: 18,
        bombletDamageRadius: 24,
        bombletTerrainRadius: 20,
        clusterSplitMinAge: 0.38,
        speedScale: 0.9,
        projectileRadius: 6,
        color: '#d7c771',
        trailColor: '230, 210, 110',
        impactVisual: 'clusterMiniBlast',
        visualType: 'split bomblets',
        fireSoundType: 'cluster',
        impactSoundType: 'cluster',
        terrainMessage: 'Cluster Bomb peppered the terrain with small craters.',
        description: 'Splits into smaller bomblets.',
        shortDescription: 'Splits into bomblets',
        statTags: ['Damage: Spread', 'Crater: Small cluster', 'Ammo: 2'],
    },
    {
        id: 'mega',
        name: 'Mega Bomb',
        compactName: 'Mega',
        inventoryName: 'Mega Bombs',
        behavior: 'crater',
        ammo: 1,
        startingAmmo: 0,
        shopRefillPrice: 375,
        maxDamage: 82,
        damageRadius: 82,
        damageFalloff: 1.85,
        terrainEffectType: 'crater',
        explosionRadius: 92,
        terrainEffectRadius: 88,
        terrainEffectStrength: 1.62,
        speedScale: 0.92,
        projectileRadius: 7,
        color: '#2b3036',
        trailColor: '255, 108, 54',
        impactVisual: 'megaBlast',
        visualType: 'largest expanding blast',
        fireSoundType: 'mega',
        impactSoundType: 'mega',
        terrainMessage: 'Mega Bomb tore open a massive crater.',
        description: 'Late-match super weapon with huge blast.',
        shortDescription: 'Huge blast, late-game',
        statTags: ['Damage: Extreme', 'Crater: Massive', 'Ammo: 1', 'Arc: Very heavy'],
    },
];

export function getWeaponById(id) {
    return WEAPONS.find((weapon) => weapon.id === id) || WEAPONS[0];
}

export function clamp(value, min, max) {
    return Math.max(min, Math.min(max, value));
}

export function maxAmmoFor(weaponId) {
    const weapon = getWeaponById(weaponId);
    return weapon ? weapon.ammo : 0;
}

export function limitedWeapons() {
    return WEAPONS.filter((weapon) => Number.isFinite(weapon.ammo));
}
